import { Sparkles, Cpu } from 'lucide-react';
import { cn } from './cn';

export type ResultMode = 'ai' | 'heuristic';

export interface ModeBadgeProps {
  /** Which engine produced the result. */
  mode: ResultMode;
  /** Hide the text label, show only the icon dot. @default false */
  iconOnly?: boolean;
  className?: string;
}

/**
 * ModeBadge — a product-defining trust signal that tells the user whether a
 * result came from the AI provider ('ai') or the deterministic fallback
 * ('heuristic'). Surfaces Jobmagic's graceful-degradation guarantee.
 */
export function ModeBadge({ mode, iconOnly = false, className }: ModeBadgeProps) {
  const isAi = mode === 'ai';
  const Icon = isAi ? Sparkles : Cpu;
  const label = isAi ? 'AI' : 'Heuristic';
  const title = isAi
    ? 'Generated by the AI provider'
    : 'Computed deterministically (works offline, no AI key needed)';

  return (
    <span
      title={title}
      aria-label={`Result mode: ${label}`}
      className={cn(
        'inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[0.6875rem] font-semibold ring-1 ring-inset',
        isAi
          ? 'bg-brand-50 text-brand-700 ring-brand-100'
          : 'bg-slate-100 text-slate-600 ring-slate-200',
        className,
      )}
    >
      <Icon className="h-3 w-3" aria-hidden="true" />
      {!iconOnly && <span>{label}</span>}
    </span>
  );
}
